# Generated by Django 3.0.5 on 2021-05-06 07:25

import accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210506_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to=accounts.models.User.content_from_file),
            preserve_default=False,
        ),
    ]
